### ISSUE TITLE
OperationalError when migrating : (1170, "BLOB/TEXT column 'url' used in key specification without a key length")

### ISSUE THREAD

**Issue by newinh** [soynatan/django-easy-audit#101]
i encountered followed error when migrating

```
easyaudit.RequestEvent.url: (fields.W162) MySQL does not support a database index on longtext columns.
        HINT: An index won't be created. Silence this warning if you don't care about it.
Operations to perform:
  Apply all migrations: easyaudit
Running migrations:
  Applying easyaudit.0001_initial... OK
  Applying easyaudit.0002_auto_20170125_0759... OK
  Applying easyaudit.0003_auto_20170228_1505... OK
  Applying easyaudit.0004_auto_20170620_1354... OK
  Applying easyaudit.0005_auto_20170713_1155... OK
  Applying easyaudit.0006_auto_20171018_1242... OK
  Applying easyaudit.0007_auto_20180105_0838... OK
  Applying easyaudit.0008_auto_20180220_1908... OK
  Applying easyaudit.0009_auto_20180314_2225...Traceback (most recent call last):
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/MySQLdb/cursors.py", line 312, in _query
    db.query(q)
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/MySQLdb/connections.py", line 224, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1170, "BLOB/TEXT column 'url' used in key specification without a key length")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/django/db/migrations/operations/fields.py", line 249, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 535, in alter_field
    old_db_params, new_db_params, strict)
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 685, in _alter_field
    params,
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/MySQLdb/cursors.py", line 312, in _query
    db.query(q)
  File "/Users/shinseunghoon/repository/toy/sample-backoffice/.venv/lib/python3.7/site-packages/MySQLdb/connections.py", line 224, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1170, "BLOB/TEXT column 'url' used in key specification without a key length")
```

python: 3.7.1
database: mysql 5.7
django: 2.2

it seems `url` field in requestevent table need index, but it didn't get index.

**Comment by jheld** [comment]
Please see issue #55 and the open PR for it.

**Comment by jheld** [comment]
Also django 2.2 support is not technically generally available (yet), but if it works for you that's great!

**Comment by jheld** [comment]
This should now be fixed if you look for the new release. It also support django 2.2. It is version 1.1.1
