### ISSUE TITLE
Programming error when migrating to 1.1.1 on re- char field 0013, postgres

### ISSUE THREAD

**Issue by AntonDeMeester** [soynatan/django-easy-audit#105]
When I run `python manage.py migrate easyaudit` I get the following error:

`django.db.utils.ProgrammingError: relation "easyaudit_requestevent_url_37d1b8c4" already exists`

Full stack:

```
File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.DuplicateTable: relation "easyaudit_requestevent_url_37d1b8c4" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/migrations/executor.py", line 121, in migrate
    state = self._migrate_all_backwards(plan, full_plan, fake=fake)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/migrations/executor.py", line 196, in _migrate_all_backwards
    self.unapply_migration(states[migration], migration, fake=fake)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/migrations/executor.py", line 269, in unapply_migration
    state = migration.unapply(state, schema_editor)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/migrations/migration.py", line 175, in unapply
    operation.database_backwards(self.app_label, schema_editor, from_state, to_state)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/migrations/operations/fields.py", line 254, in database_backwards
    self.database_forwards(app_label, schema_editor, from_state, to_state)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/migrations/operations/fields.py", line 249, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 535, in alter_field
    old_db_params, new_db_params, strict)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/backends/postgresql/schema.py", line 122, in _alter_field
    new_db_params, strict,
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 726, in _alter_field
    self.execute(self._create_index_sql(model, [new_field]))
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/antondemeester/.local/share/virtualenvs/oper-product-KNG_xSge/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "easyaudit_requestevent_url_37d1b8c4" already exists
```

It has to do something with the back and forth from textfield to charfield in the newest version.

We use Django 2.2.6, and postgresql.

When reverting to migration 0008, I also get the same error.

Any idea why this is and how we can fix this?

When I reverted to easyaudit 1.1 without the bugfix, it worked fine again.

**Comment by jheld** [comment]
So you tried upgrading to `1.1.1rc1` and found this issue?

Technically we don't fully support django `2.2` yet, though I imagine the issue you're seeing is not because of the version issue.

Did you start with a fresh database? Or did you start with having 0008 as the last completed migration? I did make a small adjustment when originally writing 0009 (I made it a TextField in 0009, but MS SQL users were unable to upgrade, so in this change I "made" it again a CharField, in this change). I didn't re-run 0009 (as my project had already run it).

I think you can fake run a given migration, but unsure that we'll need you to do that. However I'd be curious to allow you to use a `EASY_AUDIT_SKIP_MIGRATIONS=[...]` setting in your django settings. We could then potentially grab that value and choose to "run" it without actually running it, so it becomes a no-op migration. That might be a more explicit way around this. Please let me know and I'll work with you on it.

**Comment by AntonDeMeester** [comment]
Yes, I updated to 1.1.1rc1 and then this happened. 

We upgraded from the previous version 1.1 for which it worked perfectly. Before the error, the last successful full migration was 0010. When reverting to 1.1, everything migrates fine (so until 1.10).

If I look in my database directly, I see that the field is a correct `varchar 254`, so it's a bit weird that migration 0013 doesn't work.

**Comment by jheld** [comment]
Ok, version 1.1 was released before any of the changes I had introduced that people were having issues with (mostly MS SQL).

So, all I did on that change on migration 0009 was swapping to have the field not be indexed. The type didn't change. You cannot have an indexed text field (blob in many/most backends), so we had to remove that.

For version 1.1.1rc1 I swapped to put the field to a charfield (which it originally was when the field was created). Migration 0013 just adds an index to that field (no other changes).

Since we didn't have a real release for the user/content type split (among other issues there, too), you didn't see the first 0009 change (on 11/20 for post 1.1), which took the textfield's index away. The newest 0009 changes it to be a charfield w/254 length (not 255, my bad), and says no index. So, if you missed the middle 0009, then you'd simply lose 1 character, and the index. Otherwise, you'd be a text field w/no index, and then be upgraded to a char field with an index (on 0013).

So, 0009 has had a couple changes, only 1 of which didn't have a release for it. I had to make the 0009 changes because for those that couldn't run 0009, this was supposed to let them, and the newest 0009 change was just to make the field type more appropriate (and esp for new users who hadn't run the bad 0009).

But my biggest concern is: `easyaudit_requestevent_url_37d1b8c4` since that isn't a relation. It looks to be an auto-generated index name, but how could that be considered a relation? :/

**Comment by jheld** [comment]
So you said you were able to run through migration 0010. In which case yes that lines up with you having a varchar(254) which you've noted. That's great. So, that worked as expected.

00101makes the field a textfield (blob, I think). not sure why that would cause any issues.

0013 then makes it a charfield w/an index.

I agree, the field & index type swapping isn't the easiest thing to follow here, but I have no idea why 0011 would fail. It's just a column type switch.

**Comment by AntonDeMeester** [comment]
> But my biggest concern is: easyaudit_requestevent_url_37d1b8c4 since that isn't a relation. It looks to be an auto-generated index name, but how could that be considered a relation? :/

Yes indeed, I was also a bit suprised. Top of mind, I'm thinking that it might be something with the index, that it might not be removed or something because the other things are very standard. On the other hand, I'm not a database expert so that might also be completely wrong.

With the 1.1 version everything works as we expect, so we're good for now but it might be a problem in the future.

> I agree, the field & index type swapping isn't the easiest thing to follow here, but I have no idea why 0011 would fail. It's just a column type switch.

0011 and 0012 migrate fine, it's just 0013 that doesn't want to migrate.

**Comment by jheld** [comment]
We do need 1.1.1 (in some form) because its holding back other databases from upgrading effectively.

I'm unsure why you'd have the issue with the index though. Since you ran 0009, your index would have been removed. On 0011 the column type changed (and no index). Then on 0013 column type change and adding an index.

**Comment by jheld** [comment]
Makes no sense to me yet, but everything via stackoverflow articles points to similar things: https://stackoverflow.com/questions/8792912/postgresql-error-relation-already-exists

And yet, the field we're editing is not the primary key! Is there anything else at play?

**Comment by jheld** [comment]
I'm planning to release 1.1.1 as is.

We would like to help you through this. I'm not sure I understand what is going on with your system, and so far you are the only one exhibiting this issue.

Can you check deeper into the relation issue it is complaining about? Additionally, since the migration does not specify a specific index name, I wonder if you might be able to create the index (custom name) by hand and then see if that will work for you.

Assuming we don't have any migration changes needed for django 2.2 then we'll plan to move forward with official django 2.2 support and we'll work with you and anyone around migration issues, whether on the 1.1.1 tree or on (1.1.2? or 1.2 or 2.0).

**Comment by AntonDeMeester** [comment]
Sounds good. If we're the only one that reported the problem, then it shouldn't be any problem.

> You will also have to "fake" the last migration so that django will at least think it ran

I forgot about this, we'll just fake migrate the necessary systems and then we should be fine.

**Comment by jheld** [comment]
v1.1.1 has been released. Please let me know if there is anything I can help with!

**Comment by jdkizer9** [comment]
FYI, I also had this issue. Inspecting the db, the index had stayed around for some reason. I removed the index and I was able to migrate successfully.

**Comment by lorenzomorandini** [comment]
Same issue here, dropping the index fixed it. Still, it should be documented until fixed.

**Comment by jheld** [comment]
Does anyone have ideas?
Documentation is "okay" but if we can fix it for real, that would be better. Does this happen a fresh install, or just for existing projects? And is it because one of the previous migrations half worked, so it's in a weird state?

**Comment by steverecio** [comment]
Seeing this error too. I'm running django 2.2.2 and trying to update an existing database (postgres) from easy audit 1.1 to 1.2.1. Ideally just running `migrate` should allow a new version to update seamlessly instead of having to run fake commands or custom scripts.

**Comment by jheld** [comment]
yes I am aware of the ideal. i didn't have the issue -- community feedback came later. if you would like to help make a more natural code fix, you are welcome to and i would be happy to review it.
