### ISSUE TITLE
Django 3.2 support

### ISSUE THREAD

**Issue by tian-yi** [soynatan/django-easy-audit#182]
Thanks for this great package.

Django made 3.2 release a couple of days ago.

I wonder if there's any plan to upgrade django-easy-audit to be compatible with it?

Thanks!

**Comment by serge-gaia** [comment]
Django 3.2 being the new LTS, it's important.

**Comment by jheld** [comment]
Do either of you have time to create a PR for this?

**Comment by tian-yi** [comment]
I will give it a try next week.

**Comment by pembo13** [comment]
Are there known incompatibilities with Django 3.2?

**Comment by Real-Gecko** [comment]
Tried to upgrade too, tests fail with
`django.db.utils.OperationalError: database table is locked: django_session` with Django 3.2 starting from Python 3.6 up to 3.9.

**Comment by tian-yi** [comment]
Yeah, saw this error too. I guess my simple attempt to just upgrading the `setup.py` does not work. Need more work for this to work with Django 3.2 I think.

**Comment by Real-Gecko** [comment]
Actually all tests pass except one `async def test_login`, actual error happens on this line:
https://github.com/soynatan/django-easy-audit/blob/860a556d0f9314e25d99904643c2a4e18c71aa51/easyaudit/tests/test_app/tests.py#L211
I guess some ASGI features changes in 3.2.
By the way they also introduced the [DEFAULT_AUTO_FIELD](https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys) setting, so `easyaudit/tests/test_project/settings.py` is better to be updated to avoid annoying hints https://github.com/Real-Gecko/django-easy-audit/commit/8811dff8376ba869847a52e6c1519c42c316de70#

**Comment by jkarstens** [comment]
The [async `test_login`](https://github.com/soynatan/django-easy-audit/blob/860a556d0f9314e25d99904643c2a4e18c71aa51/easyaudit/tests/test_app/tests.py#L208) test failure isn't specific to Django 3.2 (it fails on Django 3.1.8 as well). 

> [Note that sync code will always be in a different thread to any async code that is calling it](https://docs.djangoproject.com/en/3.2/topics/async/). 

Since each `TestCase` test is wrapped in a transaction, this means multiple threads are accessing the same database tables within a transaction (hence the `database table is locked` error). 

Test can be fixed by extending `TransactionTestCase` instead of `TestCase` so that the test isn't running within a transaction, but I wonder if the test should just be removed altogether - what async functionality of easyaudit does this test exercise?

**Comment by jkarstens** [comment]
Ah, the asgi test case tests that `RequestEvent` captures asgi requests, makes sense. Opened #185 to fix the async login test

**Comment by jheld** [comment]
@jkarstens I've just run tests on 3.1, 3.1.8, and 3.2, and only 3.2 fails that test (`test_login (test_app.tests.TestASGIRequestEvent)`). Granted 3.2 is our target for the code change, but I want to make sure that we have a consistent environment and so would you be willing to try again on 3.1.8?

**Comment by jkarstens** [comment]
Confirmed that `test_login` from `test_app.tests.TestASGIRequestEvent` fails on Django 3.1.8 with the error mentioned above:
```
jkarstens@pop:~/django-easy-audit$ git status
HEAD detached at 860a556
nothing to commit, working tree clean
jkarstens@pop:~/django-easy-audit$ docker run -it --rm django-easy-audit bash
root@4c09a95a73fc:/code# python --version
Python 3.8.8
root@4c09a95a73fc:/code# pip freeze | grep Django
Django==3.1.8
root@4c09a95a73fc:/code# cd easyaudit/tests
root@4c09a95a73fc:/code/easyaudit/tests# ./manage.py test
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
E............................s..
======================================================================
ERROR: test_login (test_app.tests.TestASGIRequestEvent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database table is locked: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 222, in __call__
    return call_result.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 287, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/code/easyaudit/tests/test_app/tests.py", line 212, in test_login
    resp = await self.async_client.get(reverse_lazy("test_app:index"))
  File "/usr/local/lib/python3.8/site-packages/django/test/client.py", line 896, in request
    response = await self.handler(scope)
  File "/usr/local/lib/python3.8/site-packages/django/test/client.py", line 181, in __call__
    await sync_to_async(request_started.send, thread_sensitive=False)(sender=self.__class__, scope=scope)
  File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 423, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 462, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 177, in send
    return [
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/code/easyaudit/signals/request_signals.py", line 74, in request_started_handler
    session = Session.objects.get(session_key=session_id)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 425, in get
    num = len(clone)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: database table is locked: django_session

----------------------------------------------------------------------
Ran 32 tests in 1.099s

FAILED (errors=1, skipped=1)
Destroying test database for alias 'default'...
root@4c09a95a73fc:/code/easyaudit/tests# 
```

**Comment by jkarstens** [comment]
Looks like Python 3.8.8 is the culprit: tests pass on Python 3.8.7 (Django 3.1.8):
```
jkarstens@pop:~/django-easy-audit$ docker run -it --rm django-easy-audit-py387 bash
root@e57b2f28ef64:/code# cd easyaudit/tests/
root@e57b2f28ef64:/code/easyaudit/tests# ./manage.py test
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
...........................s....
----------------------------------------------------------------------
Ran 32 tests in 1.130s

OK (skipped=1)
Destroying test database for alias 'default'...
root@e57b2f28ef64:/code/easyaudit/tests# 
```

**Comment by Real-Gecko** [comment]
Any news?

**Comment by jkarstens** [comment]
#185 fixes the `TestASGIRequestEvent` test and passes checks, which I think could help Django 3.2 support - @jheld is it good to merge?

**Comment by jeanwainer** [comment]
Interested in this as well.

**Comment by Real-Gecko** [comment]
As far as I can see project maintainers are busy which is understandable. Maybe we can ask them to add another co-maintainer for the project? Who is willing to volunteer?

**Comment by OscarChangCC** [comment]
Is this something being looked at? +1 for wanting this to work with `django>=3.2`

**Comment by Real-Gecko** [comment]
Maybe @soynatan can assign collaborator to the project with the ability to merge and create new releases?
Anyone willing to step in?
