### ISSUE TITLE
pre-save DoesNotExist exception thrown when attempting to delete object that exists

### ISSUE THREAD

**Issue by josidridolfo** [soynatan/django-easy-audit#290]
First, thank you for creating and maintaining such a useful app!

I'm trying to delete an object that exists, and whenever a delete() attempt is made, easy-audit throws a DoesNotExist error and the object is not deleted.

Django 4.2.11
Postgres 16
Easy-Audit 1.3.5
Executing inside a Docker container. 
migrations have been made. 

The code:
```
    def delete_object(self):
        with transaction.atomic():
            original = type(self).objects.get(pk=self.pk)
            print(f'The object to be deleted is: {original}')
            print(f'The PK of the object to be deleted is: {original.pk}')
            print("Attempting delete!")
            on_commit(lambda: original.delete())
```

The output:
```
web-1  | The object to be deleted is: testing_delete
web-1  | The PK of the object to be deleted is: ae7ce24d-1f56-4611-9959-baf2201712bf
web-1  | Attempting delete!
web-1  | easy audit had a pre-save exception.
web-1  | Traceback (most recent call last):
web-1  |   File "/usr/local/lib/python3.12/site-packages/easyaudit/signals/model_signals.py", line 89, in pre_save
web-1  |     old_model = sender.objects.get(pk=instance.pk)
web-1  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
web-1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 637, in get
web-1  |     raise self.model.DoesNotExist(
web-1  | bids.models.Bid.DoesNotExist: Bid matching query does not exist.
```
And then a bunch of 302 errors...

Of note, when I go to a URL with the PK of the object I'm attempting to delete, the object is clearly there, as shown by the 200 status codes. 

`web-1  | [19/Apr/2024 17:39:07] "GET /bids/ae7ce24d-1f56-4611-9959-baf2201712bf HTTP/1.1" 200 5573
`

Is there any way to disable the pre-save signals, or to force a delete even if the exception is raised? Are there any other work-arounds or suggested guidance on how to ensure that extant objects can be deleted?

**Comment by josidridolfo** [comment]
Nevermind - the error was in my code!
