### ISSUE TITLE
master branch foreign key constraint on pre-save

### ISSUE THREAD

**Issue by jheld** [soynatan/django-easy-audit#54]
I'm still looking into this, but there is an issue when we try to create an object in our unit tests. It looks like it's failing in the pre-save due to a foreign key constraint.

I will be looking into it further tomorrow.

**Comment by jheld** [comment]
OK. Doesn't seem pre-save related at this point.

But, the issue definitely occurs when all of the latest migrations are applied.

**Comment by elliottcf** [comment]
Is this the error you are talking about? I think I might be running into it.

`[1521560090685] ERROR 2018-03-20 15:34:50,683 model_signals 1 139743087843136 easy audit had a pre-save exception.
[1521560090685] Traceback (most recent call last):
[1521560090685] File "/var/task/easyaudit/signals/model_signals.py", line 52, in pre_save
[1521560090685] object_json_repr = serializers.serialize("json", [instance])
[1521560090685] File "/var/task/django/core/serializers/__init__.py", line 129, in serialize
[1521560090685] s.serialize(queryset, **options)
[1521560090685] File "/var/task/django/core/serializers/base.py", line 96, in serialize
[1521560090685] self.handle_m2m_field(obj, field)
[1521560090685] File "/var/task/django/core/serializers/python.py", line 78, in handle_m2m_field
[1521560090685] m2m_value(related) for related in getattr(obj, field.name).iterator()
[1521560090685] File "/var/task/django/db/models/fields/related_descriptors.py", line 513, in __get__
[1521560090685] return self.related_manager_cls(instance)
[1521560090685] File "/var/task/django/db/models/fields/related_descriptors.py", line 830, in __init__
[1521560090685] (instance, self.pk_field_names[self.source_field_name]))
[1521560090685] ValueError: "<User: >" needs to have a value for field "id" before this many-to-many relationship can be used.`

**Comment by KonstantinSchubert** [comment]
Hi.

This happens when you have an object that has many to many relationships.

In this case, the serializers.serialize(...) call fails.


You can reproduce this by creating a Django instance of a model with many to many relationships and then trying to call serializers.serialize(...) BEFORE you save it.

Let me know if I can help with this.

**Comment by jheld** [comment]
@KonstantinSchubert  thank you for the write up. I'll look into it on my end too to verify, but in the meantime, if you have any recommendations for a solution or a PR to resolve, feel free to send it our way. I'll see if I/we can fix it, too.
