### ISSUE TITLE
TransactionManagementError While loading fixture in migration

### ISSUE THREAD

**Issue by manishgupta24** [soynatan/django-easy-audit#57]
I am trying to load a fixture in migration like:

```
fixture_dir = os.path.abspath(
    os.path.join(os.path.dirname(__file__), '../fixtures'))
fixture_filename = os.path.join(fixture_dir, 'fixtures.json')


def load_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", fixture_filename)


class Migration(migrations.Migration):

    dependencies = [
        ('sd_organizations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
```

I ran unittest like `python manage.py test`

```
This error comes up:

2018-04-05 12:10:05,989 easyaudit.signals.model_signals ERROR    easy audit had a post-save exception.
Traceback (most recent call last):
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "easyaudit_crudevent" does not exist
LINE 1: INSERT INTO "easyaudit_crudevent" ("event_type", "object_id"...
                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/easyaudit/signals/model_signals.py", line 78, in post_save
    user_pk_as_string=str(user.pk) if user else user
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "easyaudit_crudevent" does not exist
LINE 1: INSERT INTO "easyaudit_crudevent" ("event_type", "object_id"...
                    ^

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/core/management/commands/test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/core/management/commands/test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/test/runner.py", line 601, in run_tests
    old_config = self.setup_databases()
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/test/runner.py", line 546, in setup_databases
    self.parallel, **kwargs
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/test/utils.py", line 187, in setup_databases
    serialize=connection.settings_dict.get('TEST', {}).get('SERIALIZE', True),
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/backends/base/creation.py", line 69, in create_test_db
    run_syncdb=True,
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/manish/django-rest-api/sd_organizations/migrations/0002_load_initial_data.py", line 16, in load_fixture
    call_command("loaddata", fixture_filename)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 69, in handle
    self.loaddata(fixture_labels)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 109, in loaddata
    self.load_label(fixture_label)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 175, in load_label
    obj.save(using=self.using)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/core/serializers/base.py", line 205, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/models/base.py", line 905, in _save_table
    forced_update)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/models/base.py", line 955, in _do_update
    return filtered._update(values) > 0
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/models/query.py", line 664, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1204, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 889, in execute_sql
    cursor.execute(sql, params)
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 59, in execute
    self.db.validate_no_broken_transaction()
  File "/home/manish/django-rest-api/env/lib/python3.6/site-packages/django/db/backends/base/base.py", line 448, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
django.db.transaction.TransactionManagementError: Problem installing fixture '/home/manish/django-rest-api/sd_organizations/fixtures/fixtures.json': Could notload sd_organizations.OrganizationType(pk=2): An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
```

How to load fixture without triggering the audit post_save signals?

**Comment by manishgupta24** [comment]
Merge Pull Request https://github.com/soynatan/django-easy-audit/pull/58 to solve this issue.

**Comment by soynatan** [comment]
Merged. Thank you!
